export const UserAllData={
    "dailyMoney": {
        chessBetAmount:0,
        chessBetNum:0,
        chessRebateAmount: 0,
        chessWinAmount: 0,
        depositAmount: 0,
        depositArtificial: 0,
        egameBetAmount: 0,
        egameBetNum: 0,
        egameRebateAmount: 0,
        egameWinAmount: 0,
        esportBetAmount: 0,
        esportBetNum: 0,
        esportRebateAmount: 0,
        esportWinAmount: 0,
        fishingBetAmount: 0,
        fishingBetNum: 0,
        fishingRebateAmount: 0,
        fishingWinAmount: 0,
        liveBetAmount: 0,
        liveBetNum: 0,
        liveRebateAmount: 0,
        liveWinAmount: 0,
        lotBetAmount: 0,
        lotBetNum: 0,
        lotRebateAmount: 0,
        lotWinAmount: 0,
        proxyRebateAmount: 0,
        sportBetAmount: 0,
        sportBetNum: 0,
        sportRebateAmount: 0,
        sportWinAmount: 0,
        withdrawAmount: 0
    },
    "curDegreeDepositMoney": 0,
    "login": true,
    "type": 0,
    "nextDegreeDepositMoney": 0,
    "userId": 0,
    "money": 0,
    "curDegreeName": "",
    "newDegreeName": "",
    "degreeShow": true,
    "userDegreeeIcon": "",
    "newDegreeDepositMoney": 0,
    "username": ""
}
