export const colorPalletess = [
        {
          id: 1,
          backGorund: "#1C1E23",
          forGround: "#F0C059",
          first: "#141417",
          second: "#141417",
          third: "#22242A",
          text: "#68707b",
          text2: "#874404",
          text3: "#ffff",
          text4: "#ffff",
          bgImage: "/images/backgroundIMG.png",
          activeTab: "/inviteImages/F0C059.png",
          inActiveTab: "/inviteImages/1C1E23.png",
          regla: "/images/1.png",
          copy: "/copyIcons/f0c059.png",
          scroll: "/scrollImages/f0c059.png",
          fourth: "#313843",
          fifth: "#F0C059",
          sixth: "#68707b",
          sideBartext: "#d5ddff",
          gameEntryText: "#68707b",
          name: "Ferrari",
        },
        {
          id: 2,
          backGorund: "#181b29",
          forGround: "#1c64f5",
          first: "#0e121b",
          second: "#181b29",
          third: "#0e121b",
          text: "#ffffff",
          text2: "#ffffff",
          text3: "#ffffff",
          text4: "#ffff",
          bgImage: "/images/backgroundIMG.png",
          activeTab: "/inviteImages/1C64F5.png",
          inActiveTab: "/inviteImages/181b29.png",
          regla: "/images/2.png",
          copy: "/copyIcons/1c64f5.png",
          scroll: "/scrollImages/1c64f5.png",
          fourth: "#0e121b",
          fifth: "#1c64f5",
          sixth: "#1c64f5",
          sideBartext: "#d5ddff",
          gameEntryText: "#ffffff",
          name: "Bvlgari",
        },
        {
          id: 3,
          backGorund: "#1a3f45",
          forGround: "#5dcbda",
          first: "#275b66",
          second: "#1a3f45",
          third: "#275b66",
          text: "#ffffff",
          text2: "#ffffff",
          text3: "#ffffff",
          text4: "#ffff",
          bgImage: "/images/backgroundIMG.png",
          activeTab: "/inviteImages/5dcbda.png",
          inActiveTab: "/inviteImages/1a3f45.png",
          regla: "/images/3.png",
          copy: "/copyIcons/5dcbda.png",
          scroll: "/scrollImages/5dcbda.png",
          fourth: "#275b66",
          fifth: "#5dcbda",
          sixth: "#5dcbda",
          gameEntryText: "#ffffff",
          name: "Tom Ford",
        },
        {
          id: 4,
          backGorund: "#212121",
          forGround: "#e01826",
          first: "#303030",
          second: "#212121",
          third: "#303030",
          text: "#ffffff",
          text2: "#ffffff",
          text3: "#ffffff",
          text4: "#ffff",
          bgImage: "/images/backgroundIMG.png",
          activeTab: "/inviteImages/e01826.png",
          inActiveTab: "/inviteImages/212121.png",
          regla: "/images/4.png",
          copy: "/copyIcons/e01826.png",
          scroll: "/scrollImages/e01826.png",
          fourth: "#303030",
          fifth: "#e01826",
          sixth: "#e01826",
          gameEntryText: "#ffffff",
          name: "Armani",
        },
        {
          id: 5,
          backGorund: "#2a0878",
          forGround: "#d65efc",
          first: "#451f98",
          second: "#2a0878",
          third: "#451f98",
          text: "#ffffff",
          text2: "#ffffff",
          text3: "#ffffff",
          text4: "#ffff",
          bgImage: "/images/backgroundIMG.png",
          activeTab: "/inviteImages/d65efc.png",
          inActiveTab: "/inviteImages/2a0878.png",
          regla: "/images/5.png",
          copy: "/copyIcons/d65efc.png",
          scroll: "/scrollImages/d65efc.png",
          fourth: "#451f98",
          fifth: "#d65efc",
          sixth: "#d65efc",
          gameEntryText: "#ffffff",
          name: "Aston Martin",
        },
        {
          id: 6,
          backGorund: "#1d533c",
          forGround: "#fbfc50",
          first: "#22684c",
          second: "#1d533c",
          third: "#22684c",
          text: "#ffffff",
          text2: "#874404",
          text3: "#874404",
          text4: "#ffff",
          bgImage: "/images/backgroundIMG.png",
          activeTab: "/inviteImages/d65efc.png",
          inActiveTab: "/inviteImages/2a0878.png",
          regla: "/images/fbfc50.png",
          copy: "/copyIcons/Porsche_copy.png",
          scroll: "/scrollImages/Porsche.png",
          fourth: "#22684c",
          fifth: "#fbfc50",
          sixth: "#fbfc50",
          gameEntryText: "#ffffff",
          name: "Porsche",
        },
        {
          id: 7,
          backGorund: "#832422",
          forGround: "#fec506",
          first: "#a12f2f",
          second: "#832422",
          third: "#a12f2f",
          text: "#ffffff",
          text2: "#ffffff",
          text3: "#ffffff",
          text4: "#ffff",
          bgImage: "/images/backgroundIMG.png",
          activeTab: "/inviteImages/d65efc.png",
          inActiveTab: "/inviteImages/2a0878.png",
          regla: "/images/fec506.png",
          copy: "/copyIcons/Cartier_copy.png",
          scroll: "/scrollImages/Cartier.png",
          fourth: "#a12f2f",
          fifth: "#fec506",
          sixth: "#fec506",
          gameEntryText: "#ffffff",
          name: "Cartier",
        },
        {
          id: 8,
          backGorund: "#050730",
          forGround: "#f3d99e",
          first: "#12194d",
          second: "#050730",
          third: "#12194d",
          text: "#ffffff",
          text2: "#874404",
          text3: "#874404",
          text4: "#ffff",
          bgImage: "/images/backgroundIMG.png",
          activeTab: "/inviteImages/d65efc.png",
          inActiveTab: "/inviteImages/2a0878.png",
          regla: "/images/f3d99e.png",
          copy: "/copyIcons/EsteeLauder_copy.png",
          scroll: "/scrollImages/EsteeLauder.png",
          fourth: "#12194d",
          fifth: "#f3d99e",
          sixth: "#f3d99e",
          gameEntryText: "#ffffff",
          name: "Estee Lauder",
        },
        {
          id: 9,
          backGorund: "#610c21",
          forGround: "#fe3756",
          first: "#771830",
          second: "#610c21",
          third: "#771830",
          text: "#ffffff",
          text2: "#ffffff",
          text3: "#ffffff",
          text4: "#ffff",
          bgImage: "/images/backgroundIMG.png",
          activeTab: "/inviteImages/d65efc.png",
          inActiveTab: "/inviteImages/2a0878.png",
          regla: "/images/771830.png",
          copy: "/copyIcons/Burberry_copy.png",
          scroll: "/scrollImages/Burgundy.png",
          fourth: "#771830",
          fifth: "#fe3756",
          sixth: "#fe3756",
          gameEntryText: "#ffffff",
          name: "Burgundy",
        },
        {
          id: 10,
          backGorund: "#002744",
          forGround: "#04cbf4",
          first: "#013658",
          second: "#002744",
          third: "#013658",
          text: "#ffffff",
          text2: "#ffffff",
          text3: "#ffffff",
          text4: "#ffff",
          bgImage: "/images/backgroundIMG.png",
          activeTab: "/inviteImages/d65efc.png",
          inActiveTab: "/inviteImages/2a0878.png",
          regla: "/images/03395d.png",
          copy: "/copyIcons/IWC_copy.png",
          scroll: "/scrollImages/IWC.png",
          fourth: "#013658",
          fifth: "#04cbf4",
          sixth: "#04cbf4",
          gameEntryText: "#ffffff",
          name: "IWC",
        },
        {
          id: 11,
          backGorund: "#013630",
          forGround: "#fdd984",
          first: "#014c45",
          second: "#013630",
          third: "#014c45",
          text: "#ffffff",
          text2: "#874404",
          text3: "#874404",
          text4: "#ffff",
          bgImage: "/images/backgroundIMG.png",
          activeTab: "/inviteImages/d65efc.png",
          inActiveTab: "/inviteImages/2a0878.png",
          regla: "/images/fdd984.png",
          copy: "/copyIcons/Gucci_copy.png",
          scroll: "/scrollImages/Gucci.png",
          fourth: "#014c45",
          fifth: "#fdd984",
          sixth: "#fdd984",
          gameEntryText: "#ffffff",
          name: "Gucci",
        },
        {
          id: 12,
          backGorund: "#63482b",
          forGround: "#ffe5b4",
          first: "#896742",
          second: "#63482b",
          third: "#896742",
          text: "#ffffff",
          text2: "#874404",
          text3: "#874404",
          text4: "#ffff",
          bgImage: "/images/backgroundIMG.png",
          activeTab: "/inviteImages/d65efc.png",
          inActiveTab: "/inviteImages/2a0878.png",
          regla: "/images/ffe5b4.png",
          copy: "/copyIcons/Burberry_copy.png",
          scroll: "/scrollImages/Burberry.png",
          fourth: "#896742",
          fifth: "#ffe5b4",
          sixth: "#ffe5b4",
          gameEntryText: "#ffffff",
          name: "Burberry",
        },
        {
          id: 13,
          backGorund: "#034d2c",
          forGround: "#feebb0",
          first: "#086338",
          second: "#034d2c",
          third: "#086338",
          text: "#ffffff",
          text2: "#874404",
          text3: "#874404",
          text4: "#ffff",
          bgImage: "/images/backgroundIMG.png",
          activeTab: "/inviteImages/d65efc.png",
          inActiveTab: "/inviteImages/2a0878.png",
          regla: "/images/feebb0.png",
          copy: "/copyIcons/LaMer_copy.png",
          scroll: "/scrollImages/LaMer.png",
          fourth: "#086338",
          fifth: "#feebb0",
          sixth: "#feebb0",
          gameEntryText: "#ffffff",
          name: "La Mer",
        },
        {
          id: 14,
          backGorund: "#5c075c",
          forGround: "#ffda86",
          first: "#791079",
          second: "#5c075c",
          third: "#791079",
          text: "#ffffff",
          text2: "#874404",
          text3: "#874404",
          text4: "#ffff",
          bgImage: "/images/backgroundIMG.png",
          activeTab: "/inviteImages/d65efc.png",
          inActiveTab: "/inviteImages/2a0878.png",
          regla: "/images/ffda86.png",
          copy: "/copyIcons/Ebay_copy.png",
          scroll: "/scrollImages/Ebay.png",
          fourth: "#791079",
          fifth: "#ffda86",
          sixth: "#ffda86",
          gameEntryText: "#ffffff",
          name: "Ebay",
        },
        {
          id: 15,
          backGorund: "#0530a0",
          forGround: "#ffefbb",
          first: "#1642af",
          second: "#0530a0",
          third: "#1642af",
          text: "#ffffff",
          text2: "#874404",
          text3: "#874404",
          text4: "#ffff",
          bgImage: "/images/backgroundIMG.png",
          activeTab: "/inviteImages/d65efc.png",
          inActiveTab: "/inviteImages/2a0878.png",
          regla: "/images/ffefbb.png",
          copy: "/copyIcons/Dior_copy.png",
          scroll: "/scrollImages/Dior.png",
          fourth: "#1642af",
          fifth: "#ffefbb",
          sixth: "#ffefbb",
          gameEntryText: "#ffffff",
          name: "Dior",
        },
        {
          id: 16,
          backGorund: "#ECEFF6",
          forGround: "#1a2937",
          first: "#fcfcfc",
          second: "#1a2937",
          third: "#fcfcfc",
          text: "#adb6c4",
          text2: "#ffffff",
          text3: "#1a2937",
          text4: "#1a2937",
          bgImage: "/images/backgroundIMG6.png",
          activeTab: "/inviteImages/d65efc.png",
          inActiveTab: "/inviteImages/2a0878.png",
          regla: "/images/f8f8f8.png",
          copy: "/copyIcons/f8f8f8_copy.png",
          scroll: "/scrollImages/f8f8f8.png",
          fourth: "#ADB6C3",
          fifth: "#fcfcfc",
          sixth: "#1a2937",
          gameEntryText: "#adb6c4",
          name: "Burberry Blue",
        },
        {
          id: 17,
          backGorund: "#5375d1",
          forGround: "#fffcd1",
          first: "#7593e8",
          second: "#4969c2",
          third: "#7593e8",
          text: "#d5ddff",
          text2: "#b2c5fd",
          text3: "#874404",
          text4: "#ffffff",
          bgImage: "/images/backgroundIMG7.png",
          activeTab: "/inviteImages/d65efc.png",
          inActiveTab: "/inviteImages/2a0878.png",
          regla: "/images/f8f8f8.png",
          copy: "/copyIcons/f8f8f8_copy.png",
          scroll: "/scrollImages/f8f8f8.png",
          fourth: "#7593e8",
          fifth: "#fffcd1",
          sixth: "#fffcd1",
          sideBartext: "#d5ddff",
          gameEntryText: "#b2c5fd",
          name: "Furla",
    
        },
        {
          id: 18,
          backGorund: "#004684",
          forGround: "#3ccefb",
          first: "#7aa9d9",
          second: "#013c74",
          third: "#0554a1",
          text: "#7aa9d9",
          text2: "#004684",
          text3: "#7aa9d9",
          text4: "#ffff",
          bgImage: "/images/backgroundIMG.png",
          activeTab: "/inviteImages/d65efc.png",
          inActiveTab: "/inviteImages/2a0878.png",
          regla: "/images/ffefbb.png",
          copy: "/copyIcons/Dior_copy.png",
          scroll: "/scrollImages/Dior.png",
          fourth: "#7aa9d9",
          fifth: "#3ccefb",
          sixth: "#3ccefb",
          gameEntryText: "#ffffff",
          name: "Corum",
        },
        {
          id: 19,
          backGorund: "#03a0c6",
          forGround: "#fee4b4",
          first: "#d0ecf5",
          second: "#008fb1",
          third: "#12b0d3",
          text: "#d0ecf5",
          text2: "#03a0c6",
          text3: "#d0ecf5",
          text4: "#ffff",
          bgImage: "/images/backgroundIMG.png",
          activeTab: "/inviteImages/d65efc.png",
          inActiveTab: "/inviteImages/2a0878.png",
          regla: "/images/ffefbb.png",
          copy: "/copyIcons/Dior_copy.png",
          scroll: "/scrollImages/Dior.png",
          fourth: "#d0ecf5",
          fifth: "#fee4b4",
          sixth: "#fee4b4",
          gameEntryText: "#ffffff",
          name: "Twitter",
        },
        {
          id: 20,
          backGorund: "#f8f8f8",
          forGround: "#f0c059",
          first: "#fff",
          second: "#f0c059",
          third: "#fff",
          text: "#a89d81",
          text2: "#ffffff",
          text3: "#f0c059",
          text4: "#f0c059",
          bgImage: "/images/backgroundIMG21.png",
          activeTab: "/inviteImages/d65efc.png",
          inActiveTab: "/inviteImages/2a0878.png",
          regla: "/images/f8f8f8.png",
          copy: "/copyIcons/f8f8f8_copy.png",
          scroll: "/scrollImages/f8f8f8.png",
          fourth: "#ADB6C3",
          fifth: "#fff",
          sixth: "#f0c059",
          gameEntryText: "#f0c059",
          name: "McLaren",
        },
        {
          id: 21,
          backGorund: "#f8f8f8",
          forGround: "#ee777d",
          first: "#fff",
          second: "#ee777d",
          third: "#fff",
          text: "#ee777d",
          text2: "#ffffff",
          text3: "#ee777d",
          text4: "#ee777d",
          bgImage: "/images/backgroundIMG21.png",
          activeTab: "/inviteImages/d65efc.png",
          inActiveTab: "/inviteImages/2a0878.png",
          regla: "/images/f8f8f8.png",
          copy: "/copyIcons/f8f8f8_copy.png",
          scroll: "/scrollImages/f8f8f8.png",
          fourth: "#ADB6C3",
          fifth: "#fff",
          sixth: "#ee777d",
          gameEntryText: "#ee777d",
          name: "Swarovski",
        },
        {
          id: 22,
          backGorund: "#f8f8f8",
          forGround: "#137076",
          first: "#fff",
          second: "#06424A",
          third: "#fff",
          text: "#06424A",
          text2: "#ffffff",
          text3: "#ee777d",
          text4: "#ee777d",
          bgImage: "/images/backgroundIMG21.png",
          activeTab: "/inviteImages/d65efc.png",
          inActiveTab: "/inviteImages/2a0878.png",
          regla: "/images/f8f8f8.png",
          copy: "/copyIcons/f8f8f8_copy.png",
          scroll: "/scrollImages/f8f8f8.png",
          fourth: "#ADB6C3",
          fifth: "#fff",
          sixth: "#ee777d",
          gameEntryText: "#ee777d",
          name: "Valentino",
        },
        {
          id: 23,
          backGorund: "#f8f8f8",
          forGround: "#4E4E4E",
          first: "#fff",
          second: "#252525",
          third: "#fff",
          text: "#252525",
          text2: "#ffffff",
          text3: "#ee777d",
          text4: "#ee777d",
          bgImage: "/images/backgroundIMG21.png",
          activeTab: "/inviteImages/d65efc.png",
          inActiveTab: "/inviteImages/2a0878.png",
          regla: "/images/f8f8f8.png",
          copy: "/copyIcons/f8f8f8_copy.png",
          scroll: "/scrollImages/f8f8f8.png",
          fourth: "#ADB6C3",
          fifth: "#fff",
          sixth: "#ee777d",
          gameEntryText: "#ee777d",
          name: "Armani",
        },
        {
          id: 24,
          backGorund: "#f8f8f8",
          forGround: "#326E9E",
          first: "#fff",
          second: "#023F78",
          third: "#fff",
          text: "#023F78",
          text2: "#ffffff",
          text3: "#ee777d",
          text4: "#ee777d",
          bgImage: "/images/backgroundIMG21.png",
          activeTab: "/inviteImages/d65efc.png",
          inActiveTab: "/inviteImages/2a0878.png",
          regla: "/images/f8f8f8.png",
          copy: "/copyIcons/f8f8f8_copy.png",
          scroll: "/scrollImages/f8f8f8.png",
          fourth: "#ADB6C3",
          fifth: "#fff",
          sixth: "#ee777d",
          gameEntryText: "#ee777d",
          name: "Corum",
        },
        {
          id: 25,
          backGorund: "#f8f8f8",
          forGround: "#32117A",
          first: "#fff",
          second: "#513598",
          third: "#fff",
          text: "#513598",
          text2: "#ffffff",
          text3: "#ee777d",
          text4: "#ee777d",
          bgImage: "/images/backgroundIMG21.png",
          activeTab: "/inviteImages/d65efc.png",
          inActiveTab: "/inviteImages/2a0878.png",
          regla: "/images/f8f8f8.png",
          copy: "/copyIcons/f8f8f8_copy.png",
          scroll: "/scrollImages/f8f8f8.png",
          fourth: "#ADB6C3",
          fifth: "#fff",
          sixth: "#ee777d",
          gameEntryText: "#ee777d",
          name: "Aston Martin",
        },
        {
          id: 26,
          backGorund: "#f8f8f8",
          forGround: "#E87155",
          first: "#fff",
          second: "#C94725",
          third: "#fff",
          text: "#C94725",
          text2: "#ffffff",
          text3: "#ee777d",
          text4: "#ee777d",
          bgImage: "/images/backgroundIMG21.png",
          activeTab: "/inviteImages/d65efc.png",
          inActiveTab: "/inviteImages/2a0878.png",
          regla: "/images/f8f8f8.png",
          copy: "/copyIcons/f8f8f8_copy.png",
          scroll: "/scrollImages/f8f8f8.png",
          fourth: "#ADB6C3",
          fifth: "#fff",
          sixth: "#ee777d",
          gameEntryText: "#ee777d",
          name: "Carrera y Carrera",
        },
        {
          id: 27,
          backGorund: "#f8f8f8",
          forGround: "#257D60",
          first: "#fff",
          second: "#1B4E3B",
          third: "#fff",
          text: "#1B4E3B",
          text2: "#ffffff",
          text3: "#ee777d",
          text4: "#ee777d",
          bgImage: "/images/backgroundIMG21.png",
          activeTab: "/inviteImages/d65efc.png",
          inActiveTab: "/inviteImages/2a0878.png",
          regla: "/images/f8f8f8.png",
          copy: "/copyIcons/f8f8f8_copy.png",
          scroll: "/scrollImages/f8f8f8.png",
          fourth: "#ADB6C3",
          fifth: "#fff",
          sixth: "#ee777d",
          gameEntryText: "#ee777d",
          name: "Porsche",
        },
        {
          id: 28,
          backGorund: "#f8f8f8",
          forGround: "#C45962",
          first: "#fff",
          second: "#A92429",
          third: "#fff",
          text: "#A92429",
          text2: "#ffffff",
          text3: "#ee777d",
          text4: "#ee777d",
          bgImage: "/images/backgroundIMG21.png",
          activeTab: "/inviteImages/d65efc.png",
          inActiveTab: "/inviteImages/2a0878.png",
          regla: "/images/f8f8f8.png",
          copy: "/copyIcons/f8f8f8_copy.png",
          scroll: "/scrollImages/f8f8f8.png",
          fourth: "#ADB6C3",
          fifth: "#fff",
          sixth: "#ee777d",
          gameEntryText: "#ee777d",
          name: "Cartier",
        },
        {
          id: 29,
          backGorund: "#f8f8f8",
          forGround: "#4E5A8F",
          first: "#fff",
          second: "#1D286A",
          third: "#fff",
          text: "#1D286A",
          text2: "#ffffff",
          text3: "#ee777d",
          text4: "#ee777d",
          bgImage: "/images/backgroundIMG21.png",
          activeTab: "/inviteImages/d65efc.png",
          inActiveTab: "/inviteImages/2a0878.png",
          regla: "/images/f8f8f8.png",
          copy: "/copyIcons/f8f8f8_copy.png",
          scroll: "/scrollImages/f8f8f8.png",
          fourth: "#ADB6C3",
          fifth: "#fff",
          sixth: "#ee777d",
          gameEntryText: "#ee777d",
          name: "Estee Lauder ",
        },
        {
          id: 30,
          backGorund: "#f8f8f8",
          forGround: "#973F55",
          first: "#fff",
          second: "#5E0A1F",
          third: "#fff",
          text: "#5E0A1F",
          text2: "#ffffff",
          text3: "#ee777d",
          text4: "#ee777d",
          bgImage: "/images/backgroundIMG21.png",
          activeTab: "/inviteImages/d65efc.png",
          inActiveTab: "/inviteImages/2a0878.png",
          regla: "/images/f8f8f8.png",
          copy: "/copyIcons/f8f8f8_copy.png",
          scroll: "/scrollImages/f8f8f8.png",
          fourth: "#ADB6C3",
          fifth: "#fff",
          sixth: "#ee777d",
          gameEntryText: "#ee777d",
          name: "Gucci",
        },
        {
          id: 31,
          backGorund: "#f8f8f8",
          forGround: "#477691",
          first: "#fff",
          second: "#01375B",
          third: "#fff",
          text: "#01375B",
          text2: "#ffffff",
          text3: "#ee777d",
          text4: "#ee777d",
          bgImage: "/images/backgroundIMG21.png",
          activeTab: "/inviteImages/d65efc.png",
          inActiveTab: "/inviteImages/2a0878.png",
          regla: "/images/f8f8f8.png",
          copy: "/copyIcons/f8f8f8_copy.png",
          scroll: "/scrollImages/f8f8f8.png",
          fourth: "#ADB6C3",
          fifth: "#fff",
          sixth: "#ee777d",
          gameEntryText: "#ee777d",
          name: "Parmigiani Fleurier",
        },
        {
          id: 32,
          backGorund: "#f8f8f8",
          forGround: "#B9993F",
          first: "#fff",
          second: "#977C37",
          third: "#fff",
          text: "#977C37",
          text2: "#ffffff",
          text3: "#ee777d",
          text4: "#ee777d",
          bgImage: "/images/backgroundIMG21.png",
          activeTab: "/inviteImages/d65efc.png",
          inActiveTab: "/inviteImages/2a0878.png",
          regla: "/images/f8f8f8.png",
          copy: "/copyIcons/f8f8f8_copy.png",
          scroll: "/scrollImages/f8f8f8.png",
          fourth: "#ADB6C3",
          fifth: "#fff",
          sixth: "#ee777d",
          gameEntryText: "#ee777d",
          name: "Roger Vivier",
        },
        {
          id: 33,
          backGorund: "#f8f8f8",
          forGround: "#AE875D",
          first: "#fff",
          second: "#694E33",
          third: "#fff",
          text: "#694E33",
          text2: "#ffffff",
          text3: "#ee777d",
          text4: "#ee777d",
          bgImage: "/images/backgroundIMG21.png",
          activeTab: "/inviteImages/d65efc.png",
          inActiveTab: "/inviteImages/2a0878.png",
          regla: "/images/f8f8f8.png",
          copy: "/copyIcons/f8f8f8_copy.png",
          scroll: "/scrollImages/f8f8f8.png",
          fourth: "#ADB6C3",
          fifth: "#fff",
          sixth: "#ee777d",
          gameEntryText: "#ee777d",
          name: "Prada",
        },
        {
          id: 34,
          backGorund: "#f8f8f8",
          forGround: "#228458",
          first: "#fff",
          second: "#0C6339",
          third: "#fff",
          text: "#0C6339",
          text2: "#ffffff",
          text3: "#ee777d",
          text4: "#ee777d",
          bgImage: "/images/backgroundIMG21.png",
          activeTab: "/inviteImages/d65efc.png",
          inActiveTab: "/inviteImages/2a0878.png",
          regla: "/images/f8f8f8.png",
          copy: "/copyIcons/f8f8f8_copy.png",
          scroll: "/scrollImages/f8f8f8.png",
          fourth: "#ADB6C3",
          fifth: "#fff",
          sixth: "#ee777d",
          gameEntryText: "#ee777d",
          name: "Bulgari",
        },
        {
          id: 35,
          backGorund: "#f8f8f8",
          forGround: "#A04195",
          first: "#fff",
          second: "#60085F",
          third: "#fff",
          text: "#60085F",
          text2: "#ffffff",
          text3: "#ee777d",
          text4: "#ee777d",
          bgImage: "/images/backgroundIMG21.png",
          activeTab: "/inviteImages/d65efc.png",
          inActiveTab: "/inviteImages/2a0878.png",
          regla: "/images/f8f8f8.png",
          copy: "/copyIcons/f8f8f8_copy.png",
          scroll: "/scrollImages/f8f8f8.png",
          fourth: "#ADB6C3",
          fifth: "#fff",
          sixth: "#ee777d",
          gameEntryText: "#ee777d",
          name: "Lanvin",
        },
        {
          id: 36,
          backGorund: "#f8f8f8",
          forGround: "#597FE4",
          first: "#fff",
          second: "#0C43D4",
          third: "#fff",
          text: "#0C43D4",
          text2: "#ffffff",
          text3: "#ee777d",
          text4: "#ee777d",
          bgImage: "/images/backgroundIMG21.png",
          activeTab: "/inviteImages/d65efc.png",
          inActiveTab: "/inviteImages/2a0878.png",
          regla: "/images/f8f8f8.png",
          copy: "/copyIcons/f8f8f8_copy.png",
          scroll: "/scrollImages/f8f8f8.png",
          fourth: "#ADB6C3",
          fifth: "#fff",
          sixth: "#ee777d",
          gameEntryText: "#ee777d",
          name: "Montblanc",
        },
        {
          id: 37,
          backGorund: "#f8f8f8",
          forGround: "#A49383",
          first: "#fff",
          second: "#8C7A66",
          third: "#fff",
          text: "#8C7A66",
          text2: "#ffffff",
          text3: "#ee777d",
          text4: "#ee777d",
          bgImage: "/images/backgroundIMG21.png",
          activeTab: "/inviteImages/d65efc.png",
          inActiveTab: "/inviteImages/2a0878.png",
          regla: "/images/f8f8f8.png",
          copy: "/copyIcons/f8f8f8_copy.png",
          scroll: "/scrollImages/f8f8f8.png",
          fourth: "#ADB6C3",
          fifth: "#fff",
          sixth: "#ee777d",
          gameEntryText: "#ee777d",
          name: "Sergio Rossi",
        },
        {
          id: 38,
          backGorund: "#f8f8f8",
          forGround: "#6B8FF3",
          first: "#fff",
          second: "#5B7DD6",
          third: "#fff",
          text: "#5B7DD6",
          text2: "#ffffff",
          text3: "#ee777d",
          text4: "#ee777d",
          bgImage: "/images/backgroundIMG21.png",
          activeTab: "/inviteImages/d65efc.png",
          inActiveTab: "/inviteImages/2a0878.png",
          regla: "/images/f8f8f8.png",
          copy: "/copyIcons/f8f8f8_copy.png",
          scroll: "/scrollImages/f8f8f8.png",
          fourth: "#ADB6C3",
          fifth: "#fff",
          sixth: "#ee777d",
          gameEntryText: "#ee777d",
          name: "Blue Nile ",
        },
        {
          id: 39,
          backGorund: "#f8f8f8",
          forGround: "#799F8B",
          first: "#fff",
          second: "#668975",
          third: "#fff",
          text: "#668975",
          text2: "#ffffff",
          text3: "#ee777d",
          text4: "#ee777d",
          bgImage: "/images/backgroundIMG21.png",
          activeTab: "/inviteImages/d65efc.png",
          inActiveTab: "/inviteImages/2a0878.png",
          regla: "/images/f8f8f8.png",
          copy: "/copyIcons/f8f8f8_copy.png",
          scroll: "/scrollImages/f8f8f8.png",
          fourth: "#ADB6C3",
          fifth: "#fff",
          sixth: "#ee777d",
          gameEntryText: "#ee777d",
          name: "Givenchy",
        },
        {
          id: 40,
          backGorund: "#f8f8f8",
          forGround: "#5472B5",
          first: "#fff",
          second: "#0A2B6D",
          third: "#fff",
          text: "#0A2B6D",
          text2: "#ffffff",
          text3: "#ee777d",
          text4: "#ee777d",
          bgImage: "/images/backgroundIMG21.png",
          activeTab: "/inviteImages/d65efc.png",
          inActiveTab: "/inviteImages/2a0878.png",
          regla: "/images/f8f8f8.png",
          copy: "/copyIcons/f8f8f8_copy.png",
          scroll: "/scrollImages/f8f8f8.png",
          fourth: "#ADB6C3",
          fifth: "#fff",
          sixth: "#ee777d",
          gameEntryText: "#ee777d",
          name: "Cartier",
        },
        {
          id: 41,
          backGorund: "#f8f8f8",
          forGround: "#B34E65",
          first: "#fff",
          second: "#6F1129",
          third: "#fff",
          text: "#6F1129",
          text2: "#ffffff",
          text3: "#ee777d",
          text4: "#ee777d",
          bgImage: "/images/backgroundIMG21.png",
          activeTab: "/inviteImages/d65efc.png",
          inActiveTab: "/inviteImages/2a0878.png",
          regla: "/images/f8f8f8.png",
          copy: "/copyIcons/f8f8f8_copy.png",
          scroll: "/scrollImages/f8f8f8.png",
          fourth: "#ADB6C3",
          fifth: "#fff",
          sixth: "#ee777d",
          gameEntryText: "#ee777d",
          name: "Montblanc",
        },
        {
          id: 42,
          backGorund: "#f8f8f8",
          forGround: "#476491",
          first: "#fff",
          second: "#303548",
          third: "#fff",
          text: "#303548",
          text2: "#ffffff",
          text3: "#ee777d",
          text4: "#ee777d",
          bgImage: "/images/backgroundIMG21.png",
          activeTab: "/inviteImages/d65efc.png",
          inActiveTab: "/inviteImages/2a0878.png",
          regla: "/images/f8f8f8.png",
          copy: "/copyIcons/f8f8f8_copy.png",
          scroll: "/scrollImages/f8f8f8.png",
          fourth: "#ADB6C3",
          fifth: "#fff",
          sixth: "#ee777d",
          gameEntryText: "#ee777d",
          name: "Louis Vuitton",
        },
        {
          id: 43,
          backGorund: "#f8f8f8",
          forGround: "#F19449",
          first: "#fff",
          second: "#e47022",
          third: "#fff",
          text: "#e47022",
          text2: "#ffffff",
          text3: "#ee777d",
          text4: "#ee777d",
          bgImage: "/images/backgroundIMG21.png",
          activeTab: "/inviteImages/d65efc.png",
          inActiveTab: "/inviteImages/2a0878.png",
          regla: "/images/f8f8f8.png",
          copy: "/copyIcons/f8f8f8_copy.png",
          scroll: "/scrollImages/f8f8f8.png",
          fourth: "#ADB6C3",
          fifth: "#fff",
          sixth: "#ee777d",
          gameEntryText: "#ee777d",
          name: "Balenciaga",
        },
        {
          id: 44,
          backGorund: "#f8f8f8",
          forGround: "#BD9963",
          first: "#fff",
          second: "#997A41",
          third: "#fff",
          text: "#997A41",
          text2: "#ffffff",
          text3: "#ee777d",
          text4: "#ee777d",
          bgImage: "/images/backgroundIMG21.png",
          activeTab: "/inviteImages/d65efc.png",
          inActiveTab: "/inviteImages/2a0878.png",
          regla: "/images/f8f8f8.png",
          copy: "/copyIcons/f8f8f8_copy.png",
          scroll: "/scrollImages/f8f8f8.png",
          fourth: "#ADB6C3",
          fifth: "#fff",
          sixth: "#ee777d",
          gameEntryText: "#ee777d",
          name: "Brunello Cucinelli",
        },
        {
          id: 45,
          backGorund: "#f8f8f8",
          forGround: "#B37B52",
          first: "#fff",
          second: "#AA6033",
          third: "#fff",
          text: "#AA6033",
          text2: "#ffffff",
          text3: "#ee777d",
          text4: "#ee777d",
          bgImage: "/images/backgroundIMG21.png",
          activeTab: "/inviteImages/d65efc.png",
          inActiveTab: "/inviteImages/2a0878.png",
          regla: "/images/f8f8f8.png",
          copy: "/copyIcons/f8f8f8_copy.png",
          scroll: "/scrollImages/f8f8f8.png",
          fourth: "#ADB6C3",
          fifth: "#fff",
          sixth: "#ee777d",
          gameEntryText: "#ee777d",
          name: "Ralph Lauren",
        },
        {
          id: 46,
          backGorund: "#f8f8f8",
          forGround: "#CF7B96",
          first: "#fff",
          second: "#BE5E7A",
          third: "#fff",
          text: "#BE5E7A",
          text2: "#ffffff",
          text3: "#ee777d",
          text4: "#ee777d",
          bgImage: "/images/backgroundIMG21.png",
          activeTab: "/inviteImages/d65efc.png",
          inActiveTab: "/inviteImages/2a0878.png",
          regla: "/images/f8f8f8.png",
          copy: "/copyIcons/f8f8f8_copy.png",
          scroll: "/scrollImages/f8f8f8.png",
          fourth: "#ADB6C3",
          fifth: "#fff",
          sixth: "#ee777d",
          gameEntryText: "#ee777d",
          name: "Fruitz",
        },
        {
          id: 47,
          backGorund: "#f8f8f8",
          forGround: "#06973A",
          first: "#fff",
          second: "#047831",
          third: "#fff",
          text: "#047831",
          text2: "#ffffff",
          text3: "#ee777d",
          text4: "#ee777d",
          bgImage: "/images/backgroundIMG21.png",
          activeTab: "/inviteImages/d65efc.png",
          inActiveTab: "/inviteImages/2a0878.png",
          regla: "/images/f8f8f8.png",
          copy: "/copyIcons/f8f8f8_copy.png",
          scroll: "/scrollImages/f8f8f8.png",
          fourth: "#ADB6C3",
          fifth: "#fff",
          sixth: "#ee777d",
          gameEntryText: "#ee777d",
          name: "Boutallion",
        },
        {
          id: 48,
          backGorund: "#f8f8f8",
          forGround: "#8D6407",
          first: "#fff",
          second: "#E6A907",
          third: "#fff",
          text: "#E6A907",
          text2: "#ffffff",
          text3: "#ee777d",
          text4: "#ee777d",
          bgImage: "/images/backgroundIMG21.png",
          activeTab: "/inviteImages/d65efc.png",
          inActiveTab: "/inviteImages/2a0878.png",
          regla: "/images/f8f8f8.png",
          copy: "/copyIcons/f8f8f8_copy.png",
          scroll: "/scrollImages/f8f8f8.png",
          fourth: "#ADB6C3",
          fifth: "#fff",
          sixth: "#ee777d",
          gameEntryText: "#ee777d",
          name: "Oasis Italiana",
        },
        {
          id: 49,
          backGorund: "#f8f8f8",
          forGround: "#B08072",
          first: "#fff",
          second: "#81543F",
          third: "#fff",
          text: "#81543F",
          text2: "#ffffff",
          text3: "#ee777d",
          text4: "#ee777d",
          bgImage: "/images/backgroundIMG21.png",
          activeTab: "/inviteImages/d65efc.png",
          inActiveTab: "/inviteImages/2a0878.png",
          regla: "/images/f8f8f8.png",
          copy: "/copyIcons/f8f8f8_copy.png",
          scroll: "/scrollImages/f8f8f8.png",
          fourth: "#ADB6C3",
          fifth: "#fff",
          sixth: "#ee777d",
          gameEntryText: "#ee777d",
          name: "Ghiso",
        },
        {
          id: 50,
          backGorund: "#f8f8f8",
          forGround: "#57379D",
          first: "#fff",
          second: "#101010",
          third: "#fff",
          text: "#101010",
          text2: "#ffffff",
          text3: "#ee777d",
          text4: "#ee777d",
          bgImage: "/images/backgroundIMG21.png",
          activeTab: "/inviteImages/d65efc.png",
          inActiveTab: "/inviteImages/2a0878.png",
          regla: "/images/f8f8f8.png",
          copy: "/copyIcons/f8f8f8_copy.png",
          scroll: "/scrollImages/f8f8f8.png",
          fourth: "#ADB6C3",
          fifth: "#fff",
          sixth: "#ee777d",
          gameEntryText: "#ee777d",
          name: "Chanel",
        },
        {
          id: 51,
          backGorund: "#f8f8f8",
          forGround: "#BC394A",
          first: "#fff",
          second: "#740A16",
          third: "#fff",
          text: "#740A16",
          text2: "#ffffff",
          text3: "#ee777d",
          text4: "#ee777d",
          bgImage: "/images/backgroundIMG21.png",
          activeTab: "/inviteImages/d65efc.png",
          inActiveTab: "/inviteImages/2a0878.png",
          regla: "/images/f8f8f8.png",
          copy: "/copyIcons/f8f8f8_copy.png",
          scroll: "/scrollImages/f8f8f8.png",
          fourth: "#ADB6C3",
          fifth: "#fff",
          sixth: "#ee777d",
          gameEntryText: "#ee777d",
          name: "Lalique",
        },
        {
          id: 52,
          backGorund: "#f8f8f8",
          forGround: "#9F90CB",
          first: "#fff",
          second: "#8065C3",
          third: "#fff",
          text: "#8065C3",
          text2: "#ffffff",
          text3: "#ee777d",
          text4: "#ee777d",
          bgImage: "/images/backgroundIMG21.png",
          activeTab: "/inviteImages/d65efc.png",
          inActiveTab: "/inviteImages/2a0878.png",
          regla: "/images/f8f8f8.png",
          copy: "/copyIcons/f8f8f8_copy.png",
          scroll: "/scrollImages/f8f8f8.png",
          fourth: "#ADB6C3",
          fifth: "#fff",
          sixth: "#ee777d",
          gameEntryText: "#ee777d",
          name: "Dior",
        },
        {
          id: 53,
          backGorund: "#f8f8f8",
          forGround: "#609BE6",
          first: "#fff",
          second: "#1873E5",
          third: "#fff",
          text: "#1873E5",
          text2: "#ffffff",
          text3: "#ee777d",
          text4: "#ee777d",
          bgImage: "/images/backgroundIMG21.png",
          activeTab: "/inviteImages/d65efc.png",
          inActiveTab: "/inviteImages/2a0878.png",
          regla: "/images/f8f8f8.png",
          copy: "/copyIcons/f8f8f8_copy.png",
          scroll: "/scrollImages/f8f8f8.png",
          fourth: "#ADB6C3",
          fifth: "#fff",
          sixth: "#ee777d",
          gameEntryText: "#ee777d",
          name: "Tiffany",
        },
        {
          id: 54,
          backGorund: "#f8f8f8",
          forGround: "#59AF67",
          first: "#fff",
          second: "#46A056",
          third: "#fff",
          text: "#46A056",
          text2: "#ffffff",
          text3: "#ee777d",
          text4: "#ee777d",
          bgImage: "/images/backgroundIMG21.png",
          activeTab: "/inviteImages/d65efc.png",
          inActiveTab: "/inviteImages/2a0878.png",
          regla: "/images/f8f8f8.png",
          copy: "/copyIcons/f8f8f8_copy.png",
          scroll: "/scrollImages/f8f8f8.png",
          fourth: "#ADB6C3",
          fifth: "#fff",
          sixth: "#ee777d",
          gameEntryText: "#ee777d",
          name: "Salvatore Ferragamo",
        },
        {
          id: 55,
          backGorund: "#f8f8f8",
          forGround: "#38BDFD",
          first: "#fff",
          second: "#18A2EB",
          third: "#fff",
          text: "#18A2EB",
          text2: "#ffffff",
          text3: "#ee777d",
          text4: "#ee777d",
          bgImage: "/images/backgroundIMG21.png",
          activeTab: "/inviteImages/d65efc.png",
          inActiveTab: "/inviteImages/2a0878.png",
          regla: "/images/f8f8f8.png",
          copy: "/copyIcons/f8f8f8_copy.png",
          scroll: "/scrollImages/f8f8f8.png",
          fourth: "#ADB6C3",
          fifth: "#fff",
          sixth: "#ee777d",
          gameEntryText: "#ee777d",
          name: "FENDI",
        },
        {
          id: 56,
          backGorund: "#f8f8f8",
          forGround: "#45C89E",
          first: "#fff",
          second: "#22A37C",
          third: "#fff",
          text: "#22A37C",
          text2: "#ffffff",
          text3: "#ee777d",
          text4: "#ee777d",
          bgImage: "/images/backgroundIMG21.png",
          activeTab: "/inviteImages/d65efc.png",
          inActiveTab: "/inviteImages/2a0878.png",
          regla: "/images/f8f8f8.png",
          copy: "/copyIcons/f8f8f8_copy.png",
          scroll: "/scrollImages/f8f8f8.png",
          fourth: "#ADB6C3",
          fifth: "#fff",
          sixth: "#ee777d",
          gameEntryText: "#ee777d",
          name: "Chaumet",
        },
        {
          id: 57,
          backGorund: "#f8f8f8",
          forGround: "#E9505A",
          first: "#fff",
          second: "#C8272C",
          third: "#fff",
          text: "#C8272C",
          text2: "#ffffff",
          text3: "#ee777d",
          text4: "#ee777d",
          bgImage: "/images/backgroundIMG21.png",
          activeTab: "/inviteImages/d65efc.png",
          inActiveTab: "/inviteImages/2a0878.png",
          regla: "/images/f8f8f8.png",
          copy: "/copyIcons/f8f8f8_copy.png",
          scroll: "/scrollImages/f8f8f8.png",
          fourth: "#ADB6C3",
          fifth: "#fff",
          sixth: "#ee777d",
          gameEntryText: "#ee777d",
          name: "Van Cleef",
        },
        {
          id: 58,
          backGorund: "#f8f8f8",
          forGround: "#23ADC3",
          first: "#fff",
          second: "#0993B0",
          third: "#fff",
          text: "#0993B0",
          text2: "#ffffff",
          text3: "#ee777d",
          text4: "#ee777d",
          bgImage: "/images/backgroundIMG21.png",
          activeTab: "/inviteImages/d65efc.png",
          inActiveTab: "/inviteImages/2a0878.png",
          regla: "/images/f8f8f8.png",
          copy: "/copyIcons/f8f8f8_copy.png",
          scroll: "/scrollImages/f8f8f8.png",
          fourth: "#ADB6C3",
          fifth: "#fff",
          sixth: "#ee777d",
          gameEntryText: "#ee777d",
          name: "L'Occitane ",
        },
        {
          id: 59,
          backGorund: "#f8f8f8",
          forGround: "#1A625B",
          first: "#fff",
          second: "#003630",
          third: "#fff",
          text: "#003630",
          text2: "#ffffff",
          text3: "#ee777d",
          text4: "#ee777d",
          bgImage: "/images/backgroundIMG21.png",
          activeTab: "/inviteImages/d65efc.png",
          inActiveTab: "/inviteImages/2a0878.png",
          regla: "/images/f8f8f8.png",
          copy: "/copyIcons/f8f8f8_copy.png",
          scroll: "/scrollImages/f8f8f8.png",
          fourth: "#ADB6C3",
          fifth: "#fff",
          sixth: "#ee777d",
          gameEntryText: "#ee777d",
          name: "Gucci",
        },
        {
          id: 60,
          backGorund: "#f8f8f8",
          forGround: "#C06B5A",
          first: "#fff",
          second: "#AC4B3A",
          third: "#fff",
          text: "#AC4B3A",
          text2: "#ffffff",
          text3: "#ee777d",
          text4: "#ee777d",
          bgImage: "/images/backgroundIMG21.png",
          activeTab: "/inviteImages/d65efc.png",
          inActiveTab: "/inviteImages/2a0878.png",
          regla: "/images/f8f8f8.png",
          copy: "/copyIcons/f8f8f8_copy.png",
          scroll: "/scrollImages/f8f8f8.png",
          fourth: "#ADB6C3",
          fifth: "#fff",
          sixth: "#ee777d",
          gameEntryText: "#ee777d",
          name: "Chopard",
        },
        {
          id: 61,
          backGorund: "#f8f8f8",
          forGround: "#784F3E",
          first: "#fff",
          second: "#43281D",
          third: "#fff",
          text: "#43281D",
          text2: "#ffffff",
          text3: "#ee777d",
          text4: "#ee777d",
          bgImage: "/images/backgroundIMG21.png",
          activeTab: "/inviteImages/d65efc.png",
          inActiveTab: "/inviteImages/2a0878.png",
          regla: "/images/f8f8f8.png",
          copy: "/copyIcons/f8f8f8_copy.png",
          scroll: "/scrollImages/f8f8f8.png",
          fourth: "#ADB6C3",
          fifth: "#fff",
          sixth: "#ee777d",
          gameEntryText: "#ee777d",
          name: "Celine",
        },
        {
          id: 62,
          backGorund: "#f8f8f8",
          forGround: "#617A12",
          first: "#fcfcfc",
          second: "#617A12",
          third: "#fcfcfc",
          text: "#617A12",
          text2: "#ffffff",
          text3: "#617A12",
          text4: "#617A12",
          bgImage: "/images/backgroundIMG6.png",
          activeTab: "/inviteImages/d65efc.png",
          inActiveTab: "/inviteImages/2a0878.png",
          regla: "/images/f8f8f8.png",
          copy: "/copyIcons/f8f8f8_copy.png",
          scroll: "/scrollImages/f8f8f8.png",
          fourth: "#ADB6C3",
          fifth: "#fcfcfc",
          sixth: "#617A12",
          gameEntryText: "#adb6c4",
          name: "Cindy Chao",
        },
        {
          id: 63,
          backGorund: "#f8f8f8",
          forGround: "#9ECFB2",
          first: "#fcfcfc",
          second: "#9ECFB2",
          third: "#fcfcfc",
          text: "#9ECFB2",
          text2: "#ffffff",
          text3: "#9ECFB2",
          text4: "#9ECFB2",
          bgImage: "/images/backgroundIMG6.png",
          activeTab: "/inviteImages/d65efc.png",
          inActiveTab: "/inviteImages/2a0878.png",
          regla: "/images/f8f8f8.png",
          copy: "/copyIcons/f8f8f8_copy.png",
          scroll: "/scrollImages/f8f8f8.png",
          fourth: "#ADB6C3",
          fifth: "#fcfcfc",
          sixth: "#9ECFB2",
          gameEntryText: "#adb6c4",
          name: "Bottega Veneta",
        },
        {
          id: 64,
          backGorund: "#f8f8f8",
          forGround: "#618BD7",
          first: "#fcfcfc",
          second: "#618BD7",
          third: "#fcfcfc",
          text: "#618BD7",
          text2: "#ffffff",
          text3: "#618BD7",
          text4: "#618BD7",
          bgImage: "/images/backgroundIMG6.png",
          activeTab: "/inviteImages/d65efc.png",
          inActiveTab: "/inviteImages/2a0878.png",
          regla: "/images/f8f8f8.png",
          copy: "/copyIcons/f8f8f8_copy.png",
          scroll: "/scrollImages/f8f8f8.png",
          fourth: "#ADB6C3",
          fifth: "#fcfcfc",
          sixth: "#618BD7",
          gameEntryText: "#adb6c4",
          name: "Embraer",
        },
        {
          id: 65,
          backGorund: "#f8f8f8",
          forGround: "#BA5D77",
          first: "#fcfcfc",
          second: "#BA5D77",
          third: "#fcfcfc",
          text: "#BA5D77",
          text2: "#ffffff",
          text3: "#BA5D77",
          text4: "#BA5D77",
          bgImage: "/images/backgroundIMG6.png",
          activeTab: "/inviteImages/d65efc.png",
          inActiveTab: "/inviteImages/2a0878.png",
          regla: "/images/f8f8f8.png",
          copy: "/copyIcons/f8f8f8_copy.png",
          scroll: "/scrollImages/f8f8f8.png",
          fourth: "#ADB6C3",
          fifth: "#fcfcfc",
          sixth: "#BA5D77",
          gameEntryText: "#adb6c4",
          name: "Bordeaux",
        },
        {
          id: 66,
          backGorund: "#f8f8f8",
          forGround: "#445F92",
          first: "#fcfcfc",
          second: "#445F92",
          third: "#fcfcfc",
          text: "#445F92",
          text2: "#ffffff",
          text3: "#445F92",
          text4: "#445F92",
          bgImage: "/images/backgroundIMG6.png",
          activeTab: "/inviteImages/d65efc.png",
          inActiveTab: "/inviteImages/2a0878.png",
          regla: "/images/f8f8f8.png",
          copy: "/copyIcons/f8f8f8_copy.png",
          scroll: "/scrollImages/f8f8f8.png",
          fourth: "#ADB6C3",
          fifth: "#fcfcfc",
          sixth: "#445F92",
          gameEntryText: "#adb6c4",
          name: "Breduet",
        },
        {
          id: 67,
          backGorund: "#f8f8f8",
          forGround: "#FEBA82",
          first: "#fcfcfc",
          second: "#FEBA82",
          third: "#fcfcfc",
          text: "#FEBA82",
          text2: "#ffffff",
          text3: "#FEBA82",
          text4: "#FEBA82",
          bgImage: "/images/backgroundIMG6.png",
          activeTab: "/inviteImages/d65efc.png",
          inActiveTab: "/inviteImages/2a0878.png",
          regla: "/images/f8f8f8.png",
          copy: "/copyIcons/f8f8f8_copy.png",
          scroll: "/scrollImages/f8f8f8.png",
          fourth: "#ADB6C3",
          fifth: "#fcfcfc",
          sixth: "#FEBA82",
          gameEntryText: "#adb6c4",
          name: "Hermes",
        },
        {
          id: 68,
          backGorund: "#f8f8f8",
          forGround: "#AF9A6F",
          first: "#fcfcfc",
          second: "#AF9A6F",
          third: "#fcfcfc",
          text: "#AF9A6F",
          text2: "#ffffff",
          text3: "#AF9A6F",
          text4: "#AF9A6F",
          bgImage: "/images/backgroundIMG6.png",
          activeTab: "/inviteImages/d65efc.png",
          inActiveTab: "/inviteImages/2a0878.png",
          regla: "/images/f8f8f8.png",
          copy: "/copyIcons/f8f8f8_copy.png",
          scroll: "/scrollImages/f8f8f8.png",
          fourth: "#ADB6C3",
          fifth: "#fcfcfc",
          sixth: "#AF9A6F",
          gameEntryText: "#adb6c4",
          name: "CBVLGARI",
        },
        {
          id: 69,
          backGorund: "#f8f8f8",
          forGround: "#EAA07B",
          first: "#fcfcfc",
          second: "#EAA07B",
          third: "#fcfcfc",
          text: "#EAA07B",
          text2: "#ffffff",
          text3: "#EAA07B",
          text4: "#EAA07B",
          bgImage: "/images/backgroundIMG6.png",
          activeTab: "/inviteImages/d65efc.png",
          inActiveTab: "/inviteImages/2a0878.png",
          regla: "/images/f8f8f8.png",
          copy: "/copyIcons/f8f8f8_copy.png",
          scroll: "/scrollImages/f8f8f8.png",
          fourth: "#ADB6C3",
          fifth: "#fcfcfc",
          sixth: "#EAA07B",
          gameEntryText: "#adb6c4",
          name: "Hermes",
        },
        {
          id: 70,
          backGorund: "#f8f8f8",
          forGround: "#FDC0CE",
          first: "#fcfcfc",
          second: "#FDC0CE",
          third: "#fcfcfc",
          text: "#FDC0CE",
          text2: "#ffffff",
          text3: "#FDC0CE",
          text4: "#FDC0CE",
          bgImage: "/images/backgroundIMG6.png",
          activeTab: "/inviteImages/d65efc.png",
          inActiveTab: "/inviteImages/2a0878.png",
          regla: "/images/f8f8f8.png",
          copy: "/copyIcons/f8f8f8_copy.png",
          scroll: "/scrollImages/f8f8f8.png",
          fourth: "#ADB6C3",
          fifth: "#fcfcfc",
          sixth: "#FDC0CE",
          gameEntryText: "#adb6c4",
          name: "Elsa Schiaparelli",
        },
        {
          id: 71,
          backGorund: "#f8f8f8",
          forGround: "#FECFD1",
          first: "#fcfcfc",
          second: "#FECFD1",
          third: "#fcfcfc",
          text: "#FECFD1",
          text2: "#ffffff",
          text3: "#FECFD1",
          text4: "#FECFD1",
          bgImage: "/images/backgroundIMG6.png",
          activeTab: "/inviteImages/d65efc.png",
          inActiveTab: "/inviteImages/2a0878.png",
          regla: "/images/f8f8f8.png",
          copy: "/copyIcons/f8f8f8_copy.png",
          scroll: "/scrollImages/f8f8f8.png",
          fourth: "#ADB6C3",
          fifth: "#fcfcfc",
          sixth: "#FECFD1",
          gameEntryText: "#adb6c4",
          name: "Lancome",
        },
        {
          id: 72,
          backGorund: "#f8f8f8",
          forGround: "#87CF9E",
          first: "#fcfcfc",
          second: "#87CF9E",
          third: "#fcfcfc",
          text: "#87CF9E",
          text2: "#ffffff",
          text3: "#87CF9E",
          text4: "#87CF9E",
          bgImage: "/images/backgroundIMG6.png",
          activeTab: "/inviteImages/d65efc.png",
          inActiveTab: "/inviteImages/2a0878.png",
          regla: "/images/f8f8f8.png",
          copy: "/copyIcons/f8f8f8_copy.png",
          scroll: "/scrollImages/f8f8f8.png",
          fourth: "#ADB6C3",
          fifth: "#fcfcfc",
          sixth: "#87CF9E",
          gameEntryText: "#adb6c4",
          name: "Lacoste",
        },
        {
          id: 73,
          backGorund: "#f8f8f8",
          forGround: "#FFF09D",
          first: "#fcfcfc",
          second: "#FFF09D",
          third: "#fcfcfc",
          text: "#FFF09D",
          text2: "#ffffff",
          text3: "#FFF09D",
          text4: "#FFF09D",
          bgImage: "/images/backgroundIMG6.png",
          activeTab: "/inviteImages/d65efc.png",
          inActiveTab: "/inviteImages/2a0878.png",
          regla: "/images/f8f8f8.png",
          copy: "/copyIcons/f8f8f8_copy.png",
          scroll: "/scrollImages/f8f8f8.png",
          fourth: "#ADB6C3",
          fifth: "#fcfcfc",
          sixth: "#FFF09D",
          gameEntryText: "#adb6c4",
          name: "CVersace",
        },
        {
          id: 74,
          backGorund: "#f8f8f8",
          forGround: "#9B8A82",
          first: "#fcfcfc",
          second: "#9B8A82",
          third: "#fcfcfc",
          text: "#9B8A82",
          text2: "#ffffff",
          text3: "#9B8A82",
          text4: "#9B8A82",
          bgImage: "/images/backgroundIMG6.png",
          activeTab: "/inviteImages/d65efc.png",
          inActiveTab: "/inviteImages/2a0878.png",
          regla: "/images/f8f8f8.png",
          copy: "/copyIcons/f8f8f8_copy.png",
          scroll: "/scrollImages/f8f8f8.png",
          fourth: "#ADB6C3",
          fifth: "#fcfcfc",
          sixth: "#9B8A82",
          gameEntryText: "#adb6c4",
          name: "Bvlgari",
        },
        {
          id: 75,
          backGorund: "#f8f8f8",
          forGround: "#747474",
          first: "#fcfcfc",
          second: "#747474",
          third: "#fcfcfc",
          text: "#747474",
          text2: "#ffffff",
          text3: "#747474",
          text4: "#747474",
          bgImage: "/images/backgroundIMG6.png",
          activeTab: "/inviteImages/d65efc.png",
          inActiveTab: "/inviteImages/2a0878.png",
          regla: "/images/f8f8f8.png",
          copy: "/copyIcons/f8f8f8_copy.png",
          scroll: "/scrollImages/f8f8f8.png",
          fourth: "#ADB6C3",
          fifth: "#fcfcfc",
          sixth: "#747474",
          gameEntryText: "#adb6c4",
          name: "Prada",
        },
        {
          id: 76,
          backGorund: "#f8f8f8",
          forGround: "#C65865",
          first: "#fcfcfc",
          second: "#C65865",
          third: "#fcfcfc",
          text: "#C65865",
          text2: "#ffffff",
          text3: "#C65865",
          text4: "#C65865",
          bgImage: "/images/backgroundIMG6.png",
          activeTab: "/inviteImages/d65efc.png",
          inActiveTab: "/inviteImages/2a0878.png",
          regla: "/images/f8f8f8.png",
          copy: "/copyIcons/f8f8f8_copy.png",
          scroll: "/scrollImages/f8f8f8.png",
          fourth: "#ADB6C3",
          fifth: "#fcfcfc",
          sixth: "#C65865",
          gameEntryText: "#adb6c4",
          name: "Victoria Secret",
        },
        {
          id: 77,
          backGorund: "#f8f8f8",
          forGround: "#BBA6CF",
          first: "#fcfcfc",
          second: "#BBA6CF",
          third: "#fcfcfc",
          text: "#BBA6CF",
          text2: "#ffffff",
          text3: "#BBA6CF",
          text4: "#BBA6CF",
          bgImage: "/images/backgroundIMG6.png",
          activeTab: "/inviteImages/d65efc.png",
          inActiveTab: "/inviteImages/2a0878.png",
          regla: "/images/f8f8f8.png",
          copy: "/copyIcons/f8f8f8_copy.png",
          scroll: "/scrollImages/f8f8f8.png",
          fourth: "#ADB6C3",
          fifth: "#fcfcfc",
          sixth: "#BBA6CF",
          gameEntryText: "#adb6c4",
          name: "Anna Sui",
        },
        {
          id: 78,
          backGorund: "#f8f8f8",
          forGround: "#679DF5",
          first: "#fcfcfc",
          second: "#679DF5",
          third: "#fcfcfc",
          text: "#679DF5",
          text2: "#ffffff",
          text3: "#679DF5",
          text4: "#679DF5",
          bgImage: "/images/backgroundIMG6.png",
          activeTab: "/inviteImages/d65efc.png",
          inActiveTab: "/inviteImages/2a0878.png",
          regla: "/images/f8f8f8.png",
          copy: "/copyIcons/f8f8f8_copy.png",
          scroll: "/scrollImages/f8f8f8.png",
          fourth: "#ADB6C3",
          fifth: "#fcfcfc",
          sixth: "#679DF5",
          gameEntryText: "#adb6c4",
          name: "Facebook",
        },
        {
          id: 79,
          backGorund: "#f8f8f8",
          forGround: "#70DB8B",
          first: "#fcfcfc",
          second: "#70DB8B",
          third: "#fcfcfc",
          text: "#70DB8B",
          text2: "#ffffff",
          text3: "#70DB8B",
          text4: "#70DB8B",
          bgImage: "/images/backgroundIMG6.png",
          activeTab: "/inviteImages/d65efc.png",
          inActiveTab: "/inviteImages/2a0878.png",
          regla: "/images/f8f8f8.png",
          copy: "/copyIcons/f8f8f8_copy.png",
          scroll: "/scrollImages/f8f8f8.png",
          fourth: "#ADB6C3",
          fifth: "#fcfcfc",
          sixth: "#70DB8B",
          gameEntryText: "#adb6c4",
          name: "Facebook",
        },
        {
          id: 80,
          backGorund: "#f8f8f8",
          forGround: "#A7DAF7",
          first: "#fcfcfc",
          second: "#A7DAF7",
          third: "#fcfcfc",
          text: "#A7DAF7",
          text2: "#ffffff",
          text3: "#A7DAF7",
          text4: "#A7DAF7",
          bgImage: "/images/backgroundIMG6.png",
          activeTab: "/inviteImages/d65efc.png",
          inActiveTab: "/inviteImages/2a0878.png",
          regla: "/images/f8f8f8.png",
          copy: "/copyIcons/f8f8f8_copy.png",
          scroll: "/scrollImages/f8f8f8.png",
          fourth: "#ADB6C3",
          fifth: "#fcfcfc",
          sixth: "#A7DAF7",
          gameEntryText: "#adb6c4",
          name: "Twitter",
        },
        {
          id: 81,
          backGorund: "#f8f8f8",
          forGround: "#7CE1C0",
          first: "#fcfcfc",
          second: "#7CE1C0",
          third: "#fcfcfc",
          text: "#7CE1C0",
          text2: "#ffffff",
          text3: "#7CE1C0",
          text4: "#7CE1C0",
          bgImage: "/images/backgroundIMG6.png",
          activeTab: "/inviteImages/d65efc.png",
          inActiveTab: "/inviteImages/2a0878.png",
          regla: "/images/f8f8f8.png",
          copy: "/copyIcons/f8f8f8_copy.png",
          scroll: "/scrollImages/f8f8f8.png",
          fourth: "#ADB6C3",
          fifth: "#fcfcfc",
          sixth: "#7CE1C0",
          gameEntryText: "#adb6c4",
          name: "USDT",
        },
        {
          id: 82,
          backGorund: "#f8f8f8",
          forGround: "#F78487",
          first: "#fcfcfc",
          second: "#F78487",
          third: "#fcfcfc",
          text: "#F78487",
          text2: "#ffffff",
          text3: "#F78487",
          text4: "#F78487",
          bgImage: "/images/backgroundIMG6.png",
          activeTab: "/inviteImages/d65efc.png",
          inActiveTab: "/inviteImages/2a0878.png",
          regla: "/images/f8f8f8.png",
          copy: "/copyIcons/f8f8f8_copy.png",
          scroll: "/scrollImages/f8f8f8.png",
          fourth: "#ADB6C3",
          fifth: "#fcfcfc",
          sixth: "#F78487",
          gameEntryText: "#adb6c4",
          name: "SK-II",
        },
        {
          id: 83,
          backGorund: "#f8f8f8",
          forGround: "#E1CFBB",
          first: "#fcfcfc",
          second: "#E1CFBB",
          third: "#fcfcfc",
          text: "#E1CFBB",
          text2: "#ffffff",
          text3: "#E1CFBB",
          text4: "#E1CFBB",
          bgImage: "/images/backgroundIMG6.png",
          activeTab: "/inviteImages/d65efc.png",
          inActiveTab: "/inviteImages/2a0878.png",
          regla: "/images/f8f8f8.png",
          copy: "/copyIcons/f8f8f8_copy.png",
          scroll: "/scrollImages/f8f8f8.png",
          fourth: "#ADB6C3",
          fifth: "#fcfcfc",
          sixth: "#E1CFBB",
          gameEntryText: "#adb6c4",
          name: "Patek Philippe",
        },
        {
          id: 84,
          backGorund: "#f8f8f8",
          forGround: "#FABAA5",
          first: "#fcfcfc",
          second: "#FABAA5",
          third: "#fcfcfc",
          text: "#FABAA5",
          text2: "#ffffff",
          text3: "#FABAA5",
          text4: "#FABAA5",
          bgImage: "/images/backgroundIMG6.png",
          activeTab: "/inviteImages/d65efc.png",
          inActiveTab: "/inviteImages/2a0878.png",
          regla: "/images/f8f8f8.png",
          copy: "/copyIcons/f8f8f8_copy.png",
          scroll: "/scrollImages/f8f8f8.png",
          fourth: "#ADB6C3",
          fifth: "#fcfcfc",
          sixth: "#FABAA5",
          gameEntryText: "#adb6c4",
          name: "Microsoft",
        },
        {
          id: 85,
          backGorund: "#f8f8f8",
          forGround: "#FBAEA5",
          first: "#fcfcfc",
          second: "#FBAEA5",
          third: "#fcfcfc",
          text: "#FBAEA5",
          text2: "#ffffff",
          text3: "#FBAEA5",
          text4: "#FBAEA5",
          bgImage: "/images/backgroundIMG6.png",
          activeTab: "/inviteImages/d65efc.png",
          inActiveTab: "/inviteImages/2a0878.png",
          regla: "/images/f8f8f8.png",
          copy: "/copyIcons/f8f8f8_copy.png",
          scroll: "/scrollImages/f8f8f8.png",
          fourth: "#ADB6C3",
          fifth: "#fcfcfc",
          sixth: "#FBAEA5",
          gameEntryText: "#adb6c4",
          name: "3CE",
        },
        {
          id: 86,
          backGorund: "#f8f8f8",
          forGround: "#7C6054",
          first: "#fcfcfc",
          second: "#7C6054",
          third: "#fcfcfc",
          text: "#7C6054",
          text2: "#ffffff",
          text3: "#7C6054",
          text4: "#7C6054",
          bgImage: "/images/backgroundIMG6.png",
          activeTab: "/inviteImages/d65efc.png",
          inActiveTab: "/inviteImages/2a0878.png",
          regla: "/images/f8f8f8.png",
          copy: "/copyIcons/f8f8f8_copy.png",
          scroll: "/scrollImages/f8f8f8.png",
          fourth: "#ADB6C3",
          fifth: "#fcfcfc",
          sixth: "#7C6054",
          gameEntryText: "#adb6c4",
          name: "Louis Vuitton",
        },
        {
          id: 87,
          backGorund: "#f8f8f8",
          forGround: "#D7EA74",
          first: "#fcfcfc",
          second: "#D7EA74",
          third: "#fcfcfc",
          text: "#D7EA74",
          text2: "#ffffff",
          text3: "#D7EA74",
          text4: "#D7EA74",
          bgImage: "/images/backgroundIMG6.png",
          activeTab: "/inviteImages/d65efc.png",
          inActiveTab: "/inviteImages/2a0878.png",
          regla: "/images/f8f8f8.png",
          copy: "/copyIcons/f8f8f8_copy.png",
          scroll: "/scrollImages/f8f8f8.png",
          fourth: "#ADB6C3",
          fifth: "#fcfcfc",
          sixth: "#D7EA74",
          gameEntryText: "#adb6c4",
          name: "Bottega Veneta",
        },
        {
          id: 88,
          backGorund: "#f8f8f8",
          forGround: "#797979",
          first: "#fcfcfc",
          second: "#797979",
          third: "#fcfcfc",
          text: "#797979",
          text2: "#ffffff",
          text3: "#797979",
          text4: "#797979",
          bgImage: "/images/backgroundIMG6.png",
          activeTab: "/inviteImages/d65efc.png",
          inActiveTab: "/inviteImages/2a0878.png",
          regla: "/images/f8f8f8.png",
          copy: "/copyIcons/f8f8f8_copy.png",
          scroll: "/scrollImages/f8f8f8.png",
          fourth: "#ADB6C3",
          fifth: "#fcfcfc",
          sixth: "#797979",
          gameEntryText: "#adb6c4",
          name: "Ferrari",
        },
        
]
